/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AnalyticsData } from "./AnalyticsData";
import { AnalyticsDataCountArgs } from "./AnalyticsDataCountArgs";
import { AnalyticsDataFindManyArgs } from "./AnalyticsDataFindManyArgs";
import { AnalyticsDataFindUniqueArgs } from "./AnalyticsDataFindUniqueArgs";
import { CreateAnalyticsDataArgs } from "./CreateAnalyticsDataArgs";
import { UpdateAnalyticsDataArgs } from "./UpdateAnalyticsDataArgs";
import { DeleteAnalyticsDataArgs } from "./DeleteAnalyticsDataArgs";
import { AnalyticsDataService } from "../analyticsData.service";
@graphql.Resolver(() => AnalyticsData)
export class AnalyticsDataResolverBase {
  constructor(protected readonly service: AnalyticsDataService) {}

  async _analyticsDataItemsMeta(
    @graphql.Args() args: AnalyticsDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AnalyticsData])
  async analyticsDataItems(
    @graphql.Args() args: AnalyticsDataFindManyArgs
  ): Promise<AnalyticsData[]> {
    return this.service.analyticsDataItems(args);
  }

  @graphql.Query(() => AnalyticsData, { nullable: true })
  async analyticsData(
    @graphql.Args() args: AnalyticsDataFindUniqueArgs
  ): Promise<AnalyticsData | null> {
    const result = await this.service.analyticsData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyticsData)
  async createAnalyticsData(
    @graphql.Args() args: CreateAnalyticsDataArgs
  ): Promise<AnalyticsData> {
    return await this.service.createAnalyticsData({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AnalyticsData)
  async updateAnalyticsData(
    @graphql.Args() args: UpdateAnalyticsDataArgs
  ): Promise<AnalyticsData | null> {
    try {
      return await this.service.updateAnalyticsData({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AnalyticsData)
  async deleteAnalyticsData(
    @graphql.Args() args: DeleteAnalyticsDataArgs
  ): Promise<AnalyticsData | null> {
    try {
      return await this.service.deleteAnalyticsData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
