/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserData } from "./UserData";
import { UserDataCountArgs } from "./UserDataCountArgs";
import { UserDataFindManyArgs } from "./UserDataFindManyArgs";
import { UserDataFindUniqueArgs } from "./UserDataFindUniqueArgs";
import { CreateUserDataArgs } from "./CreateUserDataArgs";
import { UpdateUserDataArgs } from "./UpdateUserDataArgs";
import { DeleteUserDataArgs } from "./DeleteUserDataArgs";
import { UserDataCreateInput } from "./UserDataCreateInput";
import { ManageFeedbackResult } from "../ManageFeedbackResult";
import { UserDataService } from "../userData.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserData)
export class UserDataResolverBase {
  constructor(
    protected readonly service: UserDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "read",
    possession: "any",
  })
  async _userDataItemsMeta(
    @graphql.Args() args: UserDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserData])
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "read",
    possession: "any",
  })
  async userDataItems(
    @graphql.Args() args: UserDataFindManyArgs
  ): Promise<UserData[]> {
    return this.service.userDataItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserData, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "read",
    possession: "own",
  })
  async userData(
    @graphql.Args() args: UserDataFindUniqueArgs
  ): Promise<UserData | null> {
    const result = await this.service.userData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserData)
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "create",
    possession: "any",
  })
  async createUserData(
    @graphql.Args() args: CreateUserDataArgs
  ): Promise<UserData> {
    return await this.service.createUserData({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserData)
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "update",
    possession: "any",
  })
  async updateUserData(
    @graphql.Args() args: UpdateUserDataArgs
  ): Promise<UserData | null> {
    try {
      return await this.service.updateUserData({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserData)
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "delete",
    possession: "any",
  })
  async deleteUserData(
    @graphql.Args() args: DeleteUserDataArgs
  ): Promise<UserData | null> {
    try {
      return await this.service.deleteUserData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ManageFeedbackResult)
  async ManageFeedback(
    @graphql.Args()
    args: UserDataCreateInput
  ): Promise<ManageFeedbackResult> {
    return this.service.ManageFeedback(args);
  }
}
