/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserDataService } from "../userData.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserDataCreateInput } from "./UserDataCreateInput";
import { UserData } from "./UserData";
import { UserDataFindManyArgs } from "./UserDataFindManyArgs";
import { UserDataWhereUniqueInput } from "./UserDataWhereUniqueInput";
import { UserDataUpdateInput } from "./UserDataUpdateInput";
import { ManageFeedbackResult } from "../ManageFeedbackResult";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserDataControllerBase {
  constructor(
    protected readonly service: UserDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserData })
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserData(
    @common.Body() data: UserDataCreateInput
  ): Promise<UserData> {
    return await this.service.createUserData({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        email: true,
        telegramId: true,
        role: true,
        department: true,
        location: true,
        company: true,
        languagePreference: true,
        personalProfile: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserData] })
  @ApiNestedQuery(UserDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userDataItems(@common.Req() request: Request): Promise<UserData[]> {
    const args = plainToClass(UserDataFindManyArgs, request.query);
    return this.service.userDataItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        email: true,
        telegramId: true,
        role: true,
        department: true,
        location: true,
        company: true,
        languagePreference: true,
        personalProfile: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userData(
    @common.Param() params: UserDataWhereUniqueInput
  ): Promise<UserData | null> {
    const result = await this.service.userData({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        email: true,
        telegramId: true,
        role: true,
        department: true,
        location: true,
        company: true,
        languagePreference: true,
        personalProfile: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserData(
    @common.Param() params: UserDataWhereUniqueInput,
    @common.Body() data: UserDataUpdateInput
  ): Promise<UserData | null> {
    try {
      return await this.service.updateUserData({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          userId: true,
          email: true,
          telegramId: true,
          role: true,
          department: true,
          location: true,
          company: true,
          languagePreference: true,
          personalProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserData",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserData(
    @common.Param() params: UserDataWhereUniqueInput
  ): Promise<UserData | null> {
    try {
      return await this.service.deleteUserData({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          userId: true,
          email: true,
          telegramId: true,
          role: true,
          department: true,
          location: true,
          company: true,
          languagePreference: true,
          personalProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/manage-feedback")
  @swagger.ApiOkResponse({
    type: ManageFeedbackResult,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ManageFeedback(
    @common.Body()
    body: UserDataCreateInput
  ): Promise<ManageFeedbackResult> {
    return this.service.ManageFeedback(body);
  }
}
